// name: compute_mortgage_monthly_payment
// description: Computes the monthly payment for a mortgage.
// parameter: principal (number, required) - The principal amount of the mortgage.
// parameter: interestRate (number, required) - The The interest rate of the mortgage as a percentage between 0 and 100.
// parameter: numYears (number, required) - The life of the mortgage in years.

// Note: calculateMortgage was generated by GPT-4o on 2024-06-26

function calculateMortgage(principal, annualRate, years) {
    // Convert annual rate to monthly and decimal form
    let monthlyRate = annualRate / 100 / 12;
    // Total number of payments
    let numberOfPayments = years * 12;
    // Monthly payment formula
    let monthlyPayment = (principal * monthlyRate * Math.pow(1 + monthlyRate, numberOfPayments)) /
                         (Math.pow(1 + monthlyRate, numberOfPayments) - 1);
    return monthlyPayment;
}

return calculateMortgage(args.principal, args.interestRate, args.numYears);
